//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.27 at 05:34:21 PM ICT 
//

package com.binlah.sap.pi.mapping.domain;

import java.util.ArrayList;
import java.util.List;

public class Student {

	private String id;

	private String firstName;
	private String lastName;
	private String gender;
	private String dateOfBirth;
	private String age;
	private String email;
	protected List<NameAndValue> courses;
	protected List<NameAndValue> clubs;

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id:");
		sb.append(id);
		sb.append("\n");
		sb.append("firstName:");
		sb.append(firstName);
		sb.append("\n");
		sb.append("lastName:");
		sb.append(lastName);
		sb.append("\n");
		return sb.toString();
	}

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getAge() {
		return age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setCourses(List<NameAndValue> courses) {
		this.courses = courses;
	}

	public void setClubs(List<NameAndValue> clubs) {
		this.clubs = clubs;
	}

	/**
	 * Gets the value of the courses property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the courses property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCourses().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link NameAndValue }
	 * 
	 * 
	 */
	public List<NameAndValue> getCourses() {
		if (courses == null) {
			courses = new ArrayList<NameAndValue>();
		}
		return this.courses;
	}

	/**
	 * Gets the value of the clubs property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the clubs property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getClubs().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link NameAndValue }
	 * 
	 * 
	 */
	public List<NameAndValue> getClubs() {
		if (clubs == null) {
			clubs = new ArrayList<NameAndValue>();
		}
		return this.clubs;
	}

}
